Implemented BUILD_HOST variable.
git-svn-id: https://trac.ccs.neu.edu/svn/larceny/trunk/larceny_src@245 c9681fa6-b8ae-40c0-a6da-707a35ad5973

diff --git a/build b/build
--- a/build
+++ b/build
@@ -10,13 +10,24 @@
 #
 # Configuration section
 
-# Valid values for $HOST: chez, larceny, larceny.bin.  Add others by 
-# editing the code.
-HOST=larceny
+# Valid values for $BUILD_HOST: 
+#   chez         Executable 'scheme' in the path (Chez Scheme v5)
+#   larceny      Executable 'larceny' in path (Larceny)
+#   larceny.bin  Executable 'larceny.bin' and heap 'sparc.heap' in
+#                directory defined by LARCENY_PATH.
+# You can add others by editing the code in this script (each host must
+# have custom code).  
+#
+# The ${BUILD_HOST:-<host>} construction allows recursive uses of build,
+# as when called from Rts/Makefile, to pick up the right host system.
+
+BUILD_HOST=${BUILD_HOST:-larceny}
+export BUILD_HOST
 
 # Path of build directory.
 # Do _NOT_ remove the LARCENY_DEF tag.  It is used by `make setup' to
 # initialize the definition of the working directory.
+
 LARCENY=/proj/will/lth/larceny/src #@LARCENY_DEF@
 
 #
@@ -53,7 +64,7 @@ usage() {
   echo "  -sparc             SPARC back-end"
   echo "  -petit             ANSI/ISO C back-end"
   echo "  -verbose, -v       be verbose"
-  ehco ""
+  echo ""
   echo "Default options are -build -larceny -sparc"
   echo ""
   echo "See also http://www.ccs.neu.edu/home/lth/larceny/developing.html"
@@ -69,7 +80,7 @@ run_development_environment() {
     fi
   fi
 
-  case $HOST in
+  case $BUILD_HOST in
     chez)
       L_HOSTDIR="Chez"
       L_HOSTNAME="Chez Scheme"
@@ -79,7 +90,7 @@ run_development_environment() {
       L_HOSTNAME="Larceny"
       ;;
     *)
-      echo "Error: bad host $HOST in run_development_environment."
+      echo "Error: bad host $BUILD_HOST in run_development_environment."
       exit 1
       ;;
   esac
@@ -114,7 +125,7 @@ END
 
 expand_file() {
   TARGET=`dirname $FILE`/`basename $FILE .mac`.c
-  echo "(define host '${HOST})" >> $TMPFILE
+  echo "(define host '${BUILD_HOST})" >> $TMPFILE
   echo "(load \"${UTIL}/expand.sch\")" >> $TMPFILE
   echo "(expand-file \"${FILE}\" \"${TARGET}\")" >> $TMPFILE
   echo "(exit)" >> $TMPFILE
@@ -122,7 +133,7 @@ expand_file() {
 }
 
 config_file() {
-  echo "(define host '${HOST})" >> $TMPFILE
+  echo "(define host '${BUILD_HOST})" >> $TMPFILE
   echo "(load \"${UTIL}/config.sch\")" >> $TMPFILE
   echo "(config \"${FILE}\")" >> $TMPFILE
   echo "(exit)" >> $TMPFILE
@@ -130,11 +141,11 @@ config_file() {
 }
 
 run_scheme() {
-  case $HOST in
+  case $BUILD_HOST in
     chez)    run_chez ;;
     larceny) run_larceny ;;
     larceny.bin) run_larceny_bin ;;
-    *)       echo "Unknown host tag $HOST"; exit 1 ;;
+    *)       echo "Unknown host tag $BUILD_HOST"; exit 1 ;;
   esac
 }
 
@@ -178,7 +189,7 @@ while [ "$1" != "" ]; do
       shift
       ;;
     -chez | -c)
-      HOST=chez; shift 
+      BUILD_HOST=chez; shift 
       ;;
     -help | -h)
       usage 0
@@ -193,10 +204,10 @@ while [ "$1" != "" ]; do
       shift
       ;;
     -larceny | -l)
-      HOST=larceny; shift
+      BUILD_HOST=larceny; shift
       ;;
     -larceny.bin | -lb) 
-      HOST=larceny.bin; shift 
+      BUILD_HOST=larceny.bin; shift 
       ;;
     -sparc)
       TARGET="sparc"
